
CREATE TABLE IF NOT EXISTS `invoices` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `price_type` tinyint(1) default NULL COMMENT '0 - cena liczona od netto (PRICE_NET), 1 - cena liczona od brutto (PRICE_GROSS)',
  `number_prefix` varchar(50) collate utf8_unicode_ci NOT NULL,
  `number_int` mediumint(8) unsigned NOT NULL,
  `number_period` varchar(10) collate utf8_unicode_ci NOT NULL,
  `number_sufix` varchar(50) collate utf8_unicode_ci NOT NULL,
  `number` varchar(100) collate utf8_unicode_ci NOT NULL,
  `invoice_date` date NULL,
  `pdf` varchar(255) collate utf8_unicode_ci default NULL,
  `related_plugin` varchar(255) collate utf8_unicode_ci default NULL,
  `related_model` varchar(255) collate utf8_unicode_ci default NULL,
  `related_row_id` char(36) collate utf8_unicode_ci default NULL,
  `seller` text collate utf8_unicode_ci,
  `buyer_is_company` tinyint(1) default NULL,
  `buyer` text collate utf8_unicode_ci,
  `items` text collate utf8_unicode_ci,
  `payments` text collate utf8_unicode_ci NOT NULL,
  `taxes` text collate utf8_unicode_ci,
  `total_net` decimal(10,2) default NULL,
  `total_tax` decimal(10,2) default NULL,
  `total_gross` decimal(10,2) default NULL,
  `total_paid` decimal(10,2) NOT NULL,
  `sent` tinyint(1) NOT NULL default '0',
  `printed` tinyint(1) NOT NULL default '0',
  `emailed` tinyint(1) NOT NULL default '0',
  `done` tinyint(1) NOT NULL default '0',
  `created` datetime default NULL,
  `modified` datetime default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `number` (`number`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

